export const youtubers = [
  { name: "MrBeast",
    age: 24,
    genre: "Entertainment",
    is_Single: true,
    subscribers: 135000000,
    country: "USA",
    joinedYear: 2012
  },
  { name: "PewDiePie",
    age: 33,
    genre: "Gaming",
    is_Single: false,
    subscribers: 111000000,
    country: "Sweden",
    joinedYear: 2010
  },
  { name: "Jake Paul",
    age: 27,
    genre: "Entertainment",
    is_Single: false,
    subscribers: 20_200_000,
    country: "USA",
    joinedYear: 2013
  },
  { name: "Mark Rober",
    age: 40,
    genre: "Science",
    is_Single: false,
    subscribers: 20_800_000,
    country: "USA",
    joinedYear: 2011
  },
  { name: "Lilly Singh",
    age: 36,
    genre: "Comedy",
    is_Single: false,
    subscribers: 15_100_000,
    country: "Canada",
    joinedYear: 2010
  },
  { name: "JennaMarbles",
    age: 37,
    genre: "Comedy",
    is_Single: true,
    subscribers: 20_400_000,
    country: "USA",
    joinedYear: 2010
  },
  { name: "Markiplier",
    age: 35,
    genre: "Gaming",
    is_Single: true,
    subscribers: 36_500_000,
    country: "USA",
    joinedYear: 2012
  },
  { name: "KSI",
    age: 30,
    genre: "Entertainment",
    is_Single: false,
    subscribers: 25_900_000,
    country: "UK",
    joinedYear: 2008
  },
  { name: "Logan Paul",
    age: 29,
    genre: "Entertainment",
    is_Single: true,
    subscribers: 23_000_000,
    country: "USA",
    joinedYear: 2013
  },
  { name: "Emma Chamberlain",
    age: 22,
    genre: "Lifestyle",
    is_Single: true,
    subscribers: 12_000_000,
    country: "USA",
    joinedYear: 2017
  },
  { name: "James Charles",
    age: 26,
    genre: "Beauty",
    is_Single: false,
    subscribers: 25_000_000,
    country: "USA",
    joinedYear: 2014
  },
  { name: "T-Series",
    age: 20,
    genre: "Music",
    is_Single: false,
    subscribers: 260_000_000,
    country: "India",
    joinedYear: 2006
  },
  { name: "VanossGaming",
    age: 32,
    genre: "Gaming",
    is_Single: true,
    subscribers: 25_700_000,
    country: "Canada",
    joinedYear: 2011
  },
  { name: "SSSniperWolf",
    age: 30,
    genre: "Gaming",
    is_Single: false,
    subscribers: 34_800_000,
    country: "UK",
    joinedYear: 2013
  },
  { name: "Dude Perfect",
    age: 37,
    genre: "Sports",
    is_Single: false,
    subscribers: 58_000_000,
    country: "USA",
    joinedYear: 2009
  },
  { name: "Rhett & Link",
    age: 43,
    genre: "Comedy",
    is_Single: false,
    subscribers: 18_800_000,
    country: "USA",
    joinedYear: 2006
  },
  { name: "NikkieTutorials",
    age: 30,
    genre: "Beauty",
    is_Single: true,
    subscribers: 14_700_000,
    country: "Netherlands",
    joinedYear: 2008
  },
  { name: "Philip DeFranco",
    age: 40,
    genre: "News",
    is_Single: false,
    subscribers: 6_300_000,
    country: "USA",
    joinedYear: 2006
  },
  { name: "MKBHD",
    age: 31,
    genre: "Tech",
    is_Single: true,
    subscribers: 17_100_000,
    country: "USA",
    joinedYear: 2008
  },
  { name: "CaseyNeistat",
    age: 40,
    genre: "Vlogging",
    is_Single: true,
    subscribers: 12_000_000,
    country: "USA",
    joinedYear: 2010
  },
  { name: "Safiya Nygaard",
    age: 33,
    genre: "Lifestyle",
    is_Single: false,
    subscribers: 9_800_000,
    country: "USA",
    joinedYear: 2015
  },
  { name: "Laura Vitale",
    age: 36,
    genre: "Food",
    is_Single: false,
    subscribers: 4_200_000,
    country: "Italy",
    joinedYear: 2010
  },
  { name: "Bon Appétit",
    age: 12,
    genre: "Food",
    is_Single: false,
    subscribers: 6_800_000,
    country: "USA",
    joinedYear: 2012
  },
  { name: "Connor Franta",
    age: 31,
    genre: "Lifestyle",
    is_Single: true,
    subscribers: 5_200_000,
    country: "USA",
    joinedYear: 2010
  },
  { name: "Liza Koshy",
    age: 28,
    genre: "Comedy",
    is_Single: true,
    subscribers: 17_000_000,
    country: "USA",
    joinedYear: 2013
  },
  { name: "Colin Furze",
    age: 44,
    genre: "Engineering",
    is_Single: false,
    subscribers: 11_600_000,
    country: "UK",
    joinedYear: 2009
  },
  { name: "EvanTubeHD",
    age: 26,
    genre: "Kids",
    is_Single: true,
    subscribers: 2_900_000,
    country: "USA",
    joinedYear: 2010
  },
  { name: "Tati Westbrook",
    age: 44,
    genre: "Beauty",
    is_Single: true,
    subscribers: 9_400_000,
    country: "USA",
    joinedYear: 2010
  }
];